on:
  push:
   branches:
    - 'main'
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js 18.14.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.14.1
      - name: Install dependencies
        run: cd testiOSApp && npm install
      - name: where are we
        run: ls -lash
      - name: Install pod dependencies
        run: |
          cd testiOSApp/ios && pod install    
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
      - name: Xcode Version
        run: /usr/bin/xcodebuild -version
      - name: let see 
        run: cd testiOSApp && npx react-native run-ios --simulator="iPhone 14"
